---
apiVersion: v1
kind: Service
metadata:
  name: welcome-ui
  namespace: welcome
spec:
  type: NodePort
  selector:
    app: welcome-ui
  ports:
    - name: apigateway
      port: 3000
      targetPort: 3000
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-ui
  namespace: welcome
spec:
  selector:
    matchLabels:
      app: welcome-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: welcome-ui
    spec:
      containers:
      - name: welcome-ui
        image: abhinavsharma9/demo:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.25"
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "HOSTNAME=${HOSTNAME}"]
        env:
        - name: TZ
          value: "Asia/Kolkata"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
